import Web3Status from 'app/components/Web3Status'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Web3 starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Web3Status />
      </div>
    </div>
  )
}
